export type AppType =
  | 'claude'
  | 'codex'
  | 'opencode'
  | 'gemini'
  | 'grok'
  | 'pi'
  | 'zcode'
  | 'dsh'
  | 'workbuddy'
  | 'codebuddy'
  | 'cline'
  | 'roo-code'
  | 'kilo-code'
  | 'qwen'
  | 'qoder'
  | 'qoder-cn'
  | 'kimi'
  | 'zed'
  | 'kiro'
  | 'reasonix'
  | 'command-code'
  | 'copilot-chat'

export type ServiceKey = 'storage' | 'pricing' | 'events' | 'scheduler' | 'watcher'

export type RequestStatus = 'success' | 'error'
