export type AppType =
  | 'claude'
  | 'codex'
  | 'opencode'
  | 'gemini'
  | 'grok'
  | 'pi'
  | 'zcode'
  | 'dsh'
  | 'workbuddy'
  | 'codebuddy'
  | 'cline'
  | 'roo-code'
  | 'kilo-code'
  | 'qwen'
  | 'qoder'
  | 'qoder-cn'
  | 'kimi'
  | 'zed'
  | 'kiro'
  | 'reasonix'
  | 'command-code'
  | 'copilot-chat'
  | 'dev-eco'
  | 'mimo'
  | 'goose'
  | 'copilot-cli'
  | 'gptme'
  | 'trae-agent'
  | 'codewhale'
  | 'droid'
  | 'minimax'

export type ServiceKey = 'storage' | 'pricing' | 'events' | 'scheduler' | 'watcher'

export type RequestStatus = 'success' | 'error'
